package com.gmuscheduler.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@SpringBootApplication
@RestController
@RequestMapping(path="/ECECourses")
@Service
public class GmuSchedulerApplication {
  
@Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @GetMapping
  public List<User> getAllUsers() {
    // This returns a JSON or XML with the users
    List<User> all = userRepository.findAll();
    return all;
  }

    @PostMapping("/add")
    public ResponseEntity<String> addCourseReviews(@RequestBody List<User> courseReviews) {
        // Process the list of course reviews here
        // You can save this data to the database or perform any other necessary operations

        try {
            // Save each course review to the database
            for (User courseReview : courseReviews) {
                System.out.println(courseReview.getC_id());
                userRepository.save(courseReview);
            }

            return new ResponseEntity<>("Course reviews saved successfully", HttpStatus.OK);
        } catch (Exception e) {
            return new ResponseEntity<>("Error saving course reviews", HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

	public static void main(String[] args) {
		SpringApplication.run(GmuSchedulerApplication.class, args);
	}
}
